# This file was derived from:
# https://github.com/intel/project-example-for-python/blob/master/.github/workflows/testing.yml
name: Common CI Checks

on: push 

defaults:
  run:
    shell: sh -xeuo pipefail {0}

jobs:
  style:
    name: Style
    runs-on: k8s
    container:
      # If we want anything form docker hub, use
      #   cache-registry.caas.intel.com/cache/
      # instead of docker.io/ to avoid rate limit.
      # - library/ is for offical images
      # - <namespace>/ is for everything else
      image: cache-registry.caas.intel.com/cache/library/python:3.9-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install black==22.3.0
    - name: Run check
      run: |
        black --check .
  commit_per_pr:
    name: 1 Commit per PR
    runs-on: k8s
    container:
      image: cache-registry.caas.intel.com/cache/library/debian:latest
    env:
      BRANCH: ${{ github.base_ref }}
    steps:
    - name: Install depedencies
      run: |
        apt-get update
        apt-get install -y git
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run check
      run: |
        number_of_patches=$(git format-patch "${BRANCH}..HEAD" | wc -l)
        if [[ "x${number_of_patches}" != "x1" ]]; then
          echo "Please only create PRs containing a single commit" >&2
          exit 1
        fi
  no_binaries:
    name: No Binaries Added
    runs-on: k8s
    container:
      image: cache-registry.caas.intel.com/cache/library/debian:latest
    env:
      BRANCH: ${{ github.base_ref }}
    steps:
    - name: Install depedencies
      run: |
        apt-get update
        apt-get install -y git
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run check
      env:
        BRANCH: ${{ github.base_ref }}
      run: |
        set -ex
        patches=$(git format-patch "${BRANCH}..HEAD")
        binaries_found=$(cat "${patches}" | grep 'GIT binary patch' | wc -l)
        if [[ "x${binaries_found}" != "x0" ]]; then
          echo "Please remove any binaries you added" >&2
          exit 1
        fi
  no_files_over_100k:
    name: No Files Over 100k
    runs-on: k8s
    container:
      image: cache-registry.caas.intel.com/cache/library/debian:latest
    steps:
    - name: Install depedencies
      run: |
        apt-get update
        apt-get install -y git
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run check
      env:
        SIZE_LIMIT_BYTES: 102400
        BRANCH: ${{ github.base_ref }}
      run: |
        SAVEIFS=$IFS
        IFS=$(echo -en "\n\b")
        failure=0
        for file in $(git diff-tree --no-commit-id --name-only -r "${BRANCH}..HEAD")
        do
          size=$(stat --printf="%s" "${file}")
          if [[ "${size}" -gt "${SIZE_LIMIT_BYTES}" ]]; then
            echo "File \"${file}\" was ${size} bytes but must be less than or equal to ${SIZE_LIMIT_BYTES} bytes" >&2
            failure=1
          fi
        done
        IFS=$SAVEIFS
        if [[ "x${failure}" != "x0" ]]; then
          echo "Please fix file size issues" >&2
          exit 1
        fi
